package ru.lct.teplokontur.export;
import com.fasterxml.jackson.core.*;import com.fasterxml.jackson.databind.*;import org.locationtech.jts.geom.*;import ru.lct.teplokontur.domain.*;import ru.lct.teplokontur.engineering.*;import ru.lct.teplokontur.ingest.*;import java.io.*;import java.util.*;
public class GeoJsonResultWriter {
 private final ObjectMapper om;private final CrsTransformer crs;private final PlanEvaluator evaluator=new PlanEvaluator();
 public GeoJsonResultWriter(ObjectMapper om,CrsTransformer crs){this.om=om;this.crs=crs;}
 public void write(OutputStream out,InputSnapshot s,List<NetworkPlan> plans) throws IOException {JsonGenerator g=om.getFactory().createGenerator(out);g.writeStartObject();g.writeStringField("type","FeatureCollection");g.writeArrayFieldStart("features");int rank=1;for(NetworkPlan p:plans)writeVariant(g,s,p,rank++);g.writeEndArray();g.writeEndObject();g.flush();}
 private void writeVariant(JsonGenerator g,InputSnapshot s,NetworkPlan p,int rank)throws IOException {ReconstructionEvaluator.Result recon=evaluator.evaluate(s,p);Map<PlanNode,String> nodeIds=new IdentityHashMap<>();int seq=0;
   for(PlanNode n:p.nodes.values()){if(n.kind==NodeKind.TERMINAL){nodeIds.put(n,n.id);continue;}String id=(n.kind==NodeKind.CHAMBER?"ch_":"node_")+p.variantId+"_"+(++seq);if(n.kind==NodeKind.TIE_IN){if("heat_network".equals(n.existingObjectType)){String ch="ch_"+p.variantId+"_"+seq;writeChamber(g,p,n.point,ch,maxDn(n));nodeIds.put(n,ch);}else nodeIds.put(n,n.existingObjectId);}else{nodeIds.put(n,id);if(n.kind==NodeKind.CHAMBER||n.children.size()>1)writeChamber(g,p,n.point,id,maxDn(n));else writeTechnical(g,p,n.point,id);}}
   int edgeSeq=0,techSeq=0;for(PlanEdge e:p.edges){List<CostedRouteSegment> ss=evaluator.segments(s,e,p.mode);String start=nodeIds.get(e.parent);for(int i=0;i<ss.size();i++){CostedRouteSegment cs=ss.get(i);String end;if(i==ss.size()-1)end=nodeIds.get(e.child);else{end="tech_"+p.variantId+"_"+(++techSeq);Point pt=cs.geometry.getFactory().createPoint(cs.geometry.getCoordinateN(cs.geometry.getNumPoints()-1));writeTechnical(g,p,atDepth(pt,cs.depthEnd,p.mode),end);}writeHeatSegment(g,p,cs,"new_"+p.variantId+"_"+(++edgeSeq),start,end,i==0&&"heat_chamber".equals(e.parent.existingObjectType)?5_000_000.0:0);start=end;}}
   writeSummary(g,p,rank);
 }
 private int maxDn(PlanNode n){int d=0;if(n.parentEdge!=null)d=Math.max(d,n.parentEdge.dn);for(PlanEdge e:n.children)d=Math.max(d,e.dn);return d;}
 private void featureStart(JsonGenerator g,Geometry geom)throws IOException{g.writeStartObject();g.writeStringField("type","Feature");g.writeFieldName("geometry");if(geom==null)g.writeNull();else om.writeTree(g,GeoJsonGeometry.write(crs.toWgs(geom),om));g.writeObjectFieldStart("properties");}
 private void featureEnd(JsonGenerator g)throws IOException{g.writeEndObject();g.writeEndObject();}
 private void writeHeatSegment(JsonGenerator g,NetworkPlan p,CostedRouteSegment s,String id,String start,String end,double tieCost)throws IOException{featureStart(g,profile(s,p.mode));g.writeStringField("id",id);g.writeStringField("object_type","heat_network");g.writeStringField("variant_id",p.variantId);g.writeStringField("start_node_id",start);g.writeStringField("end_node_id",end);g.writeNumberField("flow_tph",s.flow);g.writeNumberField("diameter",s.dn);g.writeNumberField("length",s.length);g.writeStringField("laying_method",s.layingMethod);if(p.mode==RunMode.TWO_D){g.writeNullField("depth_start");g.writeNullField("depth_end");}else{g.writeNumberField("depth_start",s.depthStart);g.writeNumberField("depth_end",s.depthEnd);}g.writeNumberField("cost",s.cost);g.writeNumberField("tie_in_cost",tieCost);featureEnd(g);}
 private void writeTie(JsonGenerator g,NetworkPlan p,PlanNode n,String id)throws IOException{featureStart(g,atDepth(n.point,3,p.mode));g.writeStringField("id",id);g.writeStringField("object_type","tie_in");g.writeStringField("variant_id",p.variantId);g.writeStringField("existing_object_id",n.existingObjectId);g.writeStringField("existing_object_type",n.existingObjectType);g.writeNumberField("existing_diameter",n.existingDn==null?0:n.existingDn);g.writeNumberField("required_diameter",n.children.stream().mapToInt(e->e.dn).max().orElse(n.existingDn==null?50:n.existingDn));g.writeNumberField("cost",5_000_000.0*n.children.size());featureEnd(g);}
 private void writeChamber(JsonGenerator g,NetworkPlan p,Point pt,String id,int dn)throws IOException{featureStart(g,Double.isFinite(pt.getCoordinate().getZ())?pt:atDepth(pt,3,p.mode));g.writeStringField("id",id);g.writeStringField("object_type","heat_chamber");g.writeStringField("variant_id",p.variantId);g.writeNumberField("diameter",dn);g.writeNumberField("cost",RuleBook.chamberCost(dn));featureEnd(g);}
 private void writeTechnical(JsonGenerator g,NetworkPlan p,Point pt,String id)throws IOException{featureStart(g,Double.isFinite(pt.getCoordinate().getZ())?pt:atDepth(pt,3,p.mode));g.writeStringField("id",id);g.writeStringField("object_type","technical_node");g.writeStringField("variant_id",p.variantId);featureEnd(g);}
 private void writeRecon(JsonGenerator g,NetworkPlan p,ReconstructionRecord x,String id)throws IOException{featureStart(g,constantDepth(x.geometry,p.mode));g.writeStringField("id",id);g.writeStringField("object_type","heat_network_reconstruction");g.writeStringField("variant_id",p.variantId);g.writeStringField("existing_object_id",x.existingObjectId);g.writeNumberField("existing_flow_tph",x.existingFlow);g.writeNumberField("added_flow_tph",x.addedFlow);g.writeNumberField("calculated_flow_tph",x.calculatedFlow);g.writeNumberField("existing_diameter",x.existingDn);g.writeNumberField("required_diameter",x.requiredDn);g.writeNumberField("length",x.length);g.writeNumberField("cost",x.cost);featureEnd(g);}
 private void writeChamberRecon(JsonGenerator g,NetworkPlan p,ChamberReconstructionRecord x,Point pt,String id)throws IOException{featureStart(g,Double.isFinite(pt.getCoordinate().getZ())?pt:atDepth(pt,3,p.mode));g.writeStringField("id",id);g.writeStringField("object_type","heat_chamber_reconstruction");g.writeStringField("variant_id",p.variantId);g.writeStringField("existing_object_id",x.existingObjectId);g.writeNumberField("existing_diameter",x.existingDn);g.writeNumberField("required_diameter",x.requiredDn);g.writeNumberField("cost",x.cost);featureEnd(g);}
 private Point atDepth(Point point,double depth,RunMode mode){Coordinate c=new Coordinate(point.getCoordinate());c.setZ(mode==RunMode.DEPTH?-depth:Double.NaN);return point.getFactory().createPoint(c);}
 private Geometry constantDepth(Geometry geometry,RunMode mode){Coordinate[] coords=geometry.getCoordinates();for(int i=0;i<coords.length;i++)coords[i]=new Coordinate(coords[i].x,coords[i].y,mode==RunMode.DEPTH?-3:Double.NaN);return geometry.getFactory().createLineString(coords);}
 private LineString profile(CostedRouteSegment segment,RunMode mode){Coordinate[] coords=segment.geometry.getCoordinates();for(int i=0;i<coords.length;i++)coords[i]=new Coordinate(coords[i]);double distance=0;for(int i=0;i<coords.length;i++){if(i>0)distance+=coords[i-1].distance(coords[i]);coords[i].setZ(mode==RunMode.DEPTH?-(segment.depthStart+(segment.depthEnd-segment.depthStart)*distance/segment.length):Double.NaN);}return segment.geometry.getFactory().createLineString(coords);}
 private void writeSummary(JsonGenerator g,NetworkPlan p,int rank)throws IOException{featureStart(g,null);g.writeStringField("id","summary_"+p.variantId);g.writeStringField("object_type","variant_summary");g.writeStringField("variant_id",p.variantId);g.writeNumberField("rank",rank);g.writeNumberField("construction_cost",p.constructionCost);g.writeNumberField("chamber_construction_cost",p.chamberCost);g.writeNumberField("tie_in_cost",p.tieInCost);g.writeNumberField("reconstruction_cost",p.reconstructionCost);g.writeNumberField("chamber_reconstruction_cost",p.chamberReconstructionCost);g.writeNumberField("unconnected_penalty",p.unconnectedPenalty);g.writeNumberField("calculated_cost",p.calculatedCost);g.writeNumberField("new_network_length",p.newLength);g.writeNumberField("reconstruction_length",p.reconstructionLength);g.writeNumberField("length",p.length);g.writeNumberField("score",p.score);g.writeArrayFieldStart("unconnected_oks_ids");for(String id:p.unconnected)g.writeString(id);g.writeEndArray();featureEnd(g);}
}
