package ru.lct.teplokontur.service;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;import org.springframework.scheduling.annotation.Async;import org.springframework.stereotype.Service;import ru.lct.teplokontur.domain.*;import ru.lct.teplokontur.export.GeoJsonResultWriter;import ru.lct.teplokontur.ingest.CrsTransformer;import ru.lct.teplokontur.optimization.UniversalOptimizer;import ru.lct.teplokontur.persistence.*;import ru.lct.teplokontur.validation.OutputGeoJsonValidator;import java.io.*;import java.nio.file.*;import java.util.*;
@Service
public class OptimizationService {
 private final RunRepository runs;private final SnapshotLoader loader;private final UniversalOptimizer optimizer;private final ObjectMapper om;private final CrsTransformer crs;
 public OptimizationService(RunRepository runs,SnapshotLoader loader,UniversalOptimizer optimizer,ObjectMapper om,CrsTransformer crs){this.runs=runs;this.loader=loader;this.optimizer=optimizer;this.om=om;this.crs=crs;}
 public RunEntity create(long scenarioId,RunMode mode){RunEntity r=new RunEntity();r.scenarioId=scenarioId;r.mode=mode.name();r.status="QUEUED";r.phase="QUEUED";r.progress=0;return runs.save(r);}
 @Async("optimizerExecutor") public void execute(long runId){RunEntity r=runs.findById(runId).orElseThrow();try{r.status="RUNNING";r.phase="LOAD";r.progress=5;runs.save(r);InputSnapshot s=loader.load(r.scenarioId);r.phase="OPTIMIZE";r.progress=20;runs.save(r);RunMode mode=RunMode.valueOf(r.mode);List<NetworkPlan> plans=optimizer.optimize(s,mode);r.phase="EXPORT";r.progress=85;runs.save(r);Path dir=Paths.get(System.getProperty("java.io.tmpdir"),"teplokontur");Files.createDirectories(dir);Path out=dir.resolve("run-"+runId+".geojson");try(OutputStream os=Files.newOutputStream(out)){new GeoJsonResultWriter(om,crs).write(os,s,plans);}List<String> schemaErrors=new OutputGeoJsonValidator(om).validate(out);if(!schemaErrors.isEmpty())throw new IllegalStateException("Output schema invalid: "+schemaErrors);ArrayNode a=om.createArrayNode();int rank=1;for(NetworkPlan p:plans){ObjectNode x=om.createObjectNode();x.put("variant_id",p.variantId);x.put("rank",rank++);x.put("policy",p.policy.name());x.put("mode",p.mode.name());x.put("score",p.score);x.put("calculated_cost",p.calculatedCost);x.put("length",p.length);x.put("connected",s.terminals.size()-p.unconnected.size());x.put("total",s.terminals.size());x.put("validation_passed",p.validation!=null&&p.validation.passed);ArrayNode er=x.putArray("validation_errors"),wa=x.putArray("validation_warnings");if(p.validation!=null){for(String z:p.validation.errors)er.add(z);for(String z:p.validation.warnings)wa.add(z);}a.add(x);}r.summaryJson=a.toString();r.resultPath=out.toString();r.status="DONE";r.phase="DONE";r.progress=100;runs.save(r);}catch(Exception e){r.status="ERROR";r.phase="ERROR";r.error=e.toString();r.progress=100;runs.save(r);}}
 public Optional<RunEntity> get(long id){return runs.findById(id);}
}
