package ru.lct.teplokontur.engineering;
import org.locationtech.jts.geom.*;import org.locationtech.jts.linearref.LengthIndexedLine;import ru.lct.teplokontur.domain.*;import java.util.*;
public class ReconstructionEvaluator {
 public static final class Result {public final List<ReconstructionRecord> lines=new ArrayList<>();public final List<ChamberReconstructionRecord> chambers=new ArrayList<>();public double cost,length,chamberCost;}
 private static final class Partial {double u,flow;Partial(double u,double flow){this.u=u;this.flow=flow;}}
 public Result evaluate(InputSnapshot s,NetworkPlan p){Map<String,InputSnapshot.ExistingEdge> em=new HashMap<>();for(var e:s.network)em.put(e.id,e);Map<String,InputSnapshot.ExistingChamber> cm=new HashMap<>();for(var c:s.chambers)cm.put(c.id,c);Map<String,Double> full=new HashMap<>();Map<String,List<Partial>> partial=new HashMap<>();Map<String,List<PlanNode>> tiedChambers=new HashMap<>();
   for(PlanNode r:p.roots){double flow=r.children.stream().mapToDouble(e->e.flow).sum();String cur=r.existingObjectId;if("heat_network".equals(r.existingObjectType)){InputSnapshot.ExistingEdge edge=em.get(cur);double u=tieU(edge,r.tieChainage,em,cm,s);partial.computeIfAbsent(cur,k->new ArrayList<>()).add(new Partial(u,flow));cur=edge.upstream;}else if("heat_chamber".equals(r.existingObjectType)){tiedChambers.computeIfAbsent(cur,k->new ArrayList<>()).add(r);cur=cm.get(cur).upstream;}
     Set<String> guard=new HashSet<>();while(cur!=null&&guard.add(cur)){if(em.containsKey(cur)){full.merge(cur,flow,Double::sum);cur=em.get(cur).upstream;}else if(cm.containsKey(cur)){cur=cm.get(cur).upstream;}else break;}
   }
   Result out=new Result();for(var e:s.network){double f=full.getOrDefault(e.id,0.);List<Partial> ps=partial.getOrDefault(e.id,List.of());if(f<=1e-9&&ps.isEmpty())continue;double len=e.geometry.getLength();SortedSet<Double> bp=new TreeSet<>();bp.add(0.);if(f>0)bp.add(len);for(Partial q:ps)bp.add(Math.max(0,Math.min(len,q.u)));List<Double> b=new ArrayList<>(bp);if(b.size()==1)b.add(len);boolean upAt0=upstreamAtStart(e,em,cm,s);LengthIndexedLine li=new LengthIndexedLine(e.geometry);
     for(int i=0;i+1<b.size();i++){double a=b.get(i),z=b.get(i+1);if(z-a<1e-6)continue;double mid=(a+z)/2,add=f;for(Partial q:ps)if(q.u+1e-9>=mid)add+=q.flow;if(add<=1e-9)continue;double calc=e.flow+add;int req=RuleBook.minForFlow(calc).dn;if(req<=e.dn)continue;double ia=upAt0?a:len-a,iz=upAt0?z:len-z;LineString g=(LineString)li.extractLine(ia,iz);ReconstructionRecord rr=new ReconstructionRecord();rr.existingObjectId=e.id;rr.existingFlow=e.flow;rr.addedFlow=add;rr.calculatedFlow=calc;rr.existingDn=e.dn;rr.requiredDn=req;rr.geometry=g;rr.length=g.getLength();rr.cost=rr.length*RuleBook.byDn(req).reconCost;out.lines.add(rr);out.cost+=rr.cost;out.length+=rr.length;}
   }
   for(var ent:tiedChambers.entrySet()){InputSnapshot.ExistingChamber c=cm.get(ent.getKey());int req=c.dn;for(PlanNode root:ent.getValue())req=Math.max(req,root.children.stream().mapToInt(e->e.dn).max().orElse(c.dn));for(var edge:s.network){Coordinate a=edge.geometry.getCoordinateN(0),b=edge.geometry.getCoordinateN(edge.geometry.getNumPoints()-1);if(c.point.getCoordinate().distance(a)<2||c.point.getCoordinate().distance(b)<2){req=Math.max(req,edge.dn);for(ReconstructionRecord line:out.lines)if(line.existingObjectId.equals(edge.id)&&line.geometry.distance(c.point)<2)req=Math.max(req,line.requiredDn);}}if(req>c.dn){ChamberReconstructionRecord cr=new ChamberReconstructionRecord();cr.existingObjectId=c.id;cr.existingDn=c.dn;cr.requiredDn=req;cr.cost=RuleBook.chamberCost(req);out.chambers.add(cr);out.chamberCost+=cr.cost;}}
   return out;
 }
 private double tieU(InputSnapshot.ExistingEdge e,double idx,Map<String,InputSnapshot.ExistingEdge> em,Map<String,InputSnapshot.ExistingChamber> cm,InputSnapshot s){double len=e.geometry.getLength();return upstreamAtStart(e,em,cm,s)?Math.max(0,idx):Math.max(0,len-idx);}
 private boolean upstreamAtStart(InputSnapshot.ExistingEdge e,Map<String,InputSnapshot.ExistingEdge> em,Map<String,InputSnapshot.ExistingChamber> cm,InputSnapshot s){Geometry up=null;if(em.containsKey(e.upstream))up=em.get(e.upstream).geometry;else if(cm.containsKey(e.upstream))up=cm.get(e.upstream).point;else if(s.source!=null)up=s.source;if(up==null)return true;Coordinate a=e.geometry.getCoordinateN(0),b=e.geometry.getCoordinateN(e.geometry.getNumPoints()-1);GeometryFactory gf=e.geometry.getFactory();return gf.createPoint(a).distance(up)<=gf.createPoint(b).distance(up);}
}
