package ru.lct.teplokontur.optimization;
import ru.lct.teplokontur.domain.*;import java.util.*;
public final class VariantDiversity {
 private static final double GEOMETRY_CELL_METRES=12.0;
 public double distance(NetworkPlan a,NetworkPlan b){double ties=jaccardDistance(tieIns(a),tieIns(b));double topology=jaccardDistance(components(a),components(b));double geometry=jaccardDistance(corridorCells(a),corridorCells(b));return .35*ties+.35*topology+.30*geometry;}
 public boolean materiallyDifferent(NetworkPlan a,NetworkPlan b){return jaccardDistance(tieIns(a),tieIns(b))>=.15||jaccardDistance(components(a),components(b))>=.15||jaccardDistance(corridorCells(a),corridorCells(b))>=.25;}
 private Set<String> tieIns(NetworkPlan p){Set<String> result=new HashSet<>();for(PlanNode root:p.roots)result.add(root.existingObjectType+":"+root.existingObjectId);return result;}
 private Set<String> components(NetworkPlan p){Set<String> result=new HashSet<>();for(PlanNode root:p.roots){Set<String> terminals=new TreeSet<>();Deque<PlanNode> queue=new ArrayDeque<>();Set<PlanNode> seen=Collections.newSetFromMap(new IdentityHashMap<>());queue.add(root);while(!queue.isEmpty()){PlanNode node=queue.remove();if(!seen.add(node))continue;if(node.kind==NodeKind.TERMINAL)terminals.add(node.oksId);for(PlanEdge edge:node.children)queue.add(edge.child);}result.add(root.existingObjectType+":"+root.existingObjectId+"=>"+String.join(",",terminals));}for(PlanNode node:p.nodes.values())if(node.children.size()>1){List<String> groups=new ArrayList<>();for(PlanEdge edge:node.children){Set<String> leaves=new TreeSet<>();collectLeaves(edge.child,leaves,new HashSet<>());groups.add(String.join(",",leaves));}Collections.sort(groups);result.add("branch:"+String.join("/",groups));}return result;}
 private void collectLeaves(PlanNode node,Set<String> leaves,Set<PlanNode> seen){if(!seen.add(node))return;if(node.kind==NodeKind.TERMINAL)leaves.add(node.oksId);for(PlanEdge edge:node.children)collectLeaves(edge.child,leaves,seen);}
 private Set<String> corridorCells(NetworkPlan p){Set<String> result=new HashSet<>();for(PlanEdge edge:p.edges){org.locationtech.jts.geom.Coordinate[] coordinates=edge.geometry.getCoordinates();for(int i=0;i<coordinates.length-1;i++){org.locationtech.jts.geom.Coordinate from=coordinates[i],to=coordinates[i+1];int steps=Math.max(1,(int)Math.ceil(from.distance(to)/GEOMETRY_CELL_METRES));for(int step=0;step<=steps;step++){double ratio=step/(double)steps;long x=(long)Math.floor((from.x+(to.x-from.x)*ratio)/GEOMETRY_CELL_METRES);long y=(long)Math.floor((from.y+(to.y-from.y)*ratio)/GEOMETRY_CELL_METRES);result.add(x+":"+y);}}}return result;}
 private double jaccardDistance(Set<String> a,Set<String> b){Set<String> union=new HashSet<>(a);union.addAll(b);if(union.isEmpty())return 0;Set<String> intersection=new HashSet<>(a);intersection.retainAll(b);return 1.0-intersection.size()/(double)union.size();}
}
